SurvivalCodingCampus/polytech_java_study

- TIL/README.md
> 250609_07_이수현

- TIL/topics/java_basic/용어정리.md
- src/main/java/com/survivalcoding/Main.java
- TIL 파일 작성 후 request하기
간단한 .md 문서 작성법
1. (#)을 사용한 제목 작성
2. (| | |)을 활용해 표 만들기
3. ( - , 1. )로 작성
깃 용어 정리와 간단하게 정리하기!!
> 250609_19_최아인

- TIL/topics/java_basic/TIL-2025.06.09.md
- src/main/java/com/survivalcoding/Main.java
> 250609_11_유아리

- TIL/0609수업정리/0609수업내용정리.md
- src/main/java/com/survivalcoding/Main.java
- **교육 주제**: 
용어 개념이 확실하게 잡혀 있어야 한다는 것을 느꼈습니다
> 250609_08_남예진

- TIL/topics/git/명령어.md
#250609_12_이다영
- **교육 주제**: 
github 쓰기 아직 어색하다. 뒤돌면 까먹는다. 터미널 글씨 너무 작다.
> 250609_12_이다영

- TIL/topics/java_basic/용어정리.md
- src/main/java/com/survivalcoding/Main.java
- **교육 주제**: 
git 기본 사용법 정리 및 java 프로그래밍 환경 세팅
git 사용법
무슨 내용인지 모르고 무작정 git을 사용하다가, 과정을 이해하니 왜 해당 명령어를 써야하는지 그간 왜 오류가 났어는지 알 수 있었다.
> 250609_18_정해원

- TIL/topics/java_basic/과제제출방법.md
- TIL/topics/java_basic/용어정리.md
- src/main/java/com/survivalcoding/Main.java
> 250609_09_김민지

- src/main/java/com/survivalcoding/Kinoko.java
- src/main/java/com/survivalcoding/Main.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Cleric.java
- src/test/java/com/survivalcoding/KinokoTest.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/ClericTest.java
- **교육 주제**: 
- [O] Test 코드 작성
> # 250610_07_이수현

- TIL/topics/java_basic/TIL-2025.06.10.md
- src/main/java/com/survivalcoding/Cleric.java
- src/main/java/com/survivalcoding/Kinoko.java
- src/test/java/com/survivalcoding/ClericTest.java
- src/test/java/com/survivalcoding/KinokoTest.java
#20250610_11_유아리
- **교육 주제**: 
테스트코드 직접 해보기
- [] Lint 체크
코드가 생소한 더 생소한 자바는 정말 어색하다.
테스트코드 작성법, 자바코드를 책과 교수님 자료를 참조해서 쳐보는 배움 
이젠 나도 자바 책
어 렵 다. 최대한 소스를 머리를 굴려서 써봐도 잘 안된다. 더 공부 해야지
> 250610_11_유아리

- TIL/topics/2.Java 명명규칙 & 테스트 코드 작성/클래스와 인스턴스 간단한 정리 및 테스트 코드 작성.md
- src/main/java/com/survivalcoding/ClassIntro.java
- src/main/java/com/survivalcoding/Cleric.java
- src/main/java/com/survivalcoding/Main.java
- src/test/java/com/survivalcoding/ClericTest.java
- 자바 메서드 코딩
- 테스트 코드 작성
- given-when-then 테스트 기법 사용
- assertEquals(A, B)와 assertEquals(A, B, C)를 사용해 값 비교 및 오차 범위 탐색
테스트 케이스를 작성하면서 범위 비교 및 랜덤 값에 대한 어려움이 있었습니다
테스트 기법에 대해 완전히 배우진 않았지만, given-when-then 만으로도 테스트 케이스를 작성하며 코드를 수정할 수 있었습니다
assertEquals 오차 범위
https://tjdtls690.github.io/studycontents/java/2022-08-01-junit_01/
테스트 케이스와 관련해선 앞으로 많이 배워야 할 거 같습니다
> 250610_06_김종윤

- TIL/topics/java_basic/3차시.md
- src/main/java/com/survivalcoding/class_3/Cleric.java
- src/test/java/com/survivalcoding/class_3/ClericTest.java
- **교육 주제**:  인스턴스와 클래스
Cleric클래스를 작성한다. 
1. 클래스의 멤버 변수로는 hp, mp, MAX_HP, MAX_MP가 존재한다. 이때 MAX에 해당하는 값들은 상수로 필드로 선언한다
2. 클래스의 멤버 함수(메소드)로는 selfAid(), pray()가 있다
2-1) selfAid()
-MP를 5소비하는 것으로 자신의 HP 를 최대 HP 까지 회복할 수 있다. 
-인수와 리턴 값이 없다.
2-2) pray()
-자신의 MP를 회복한다.
-회복량은 기도한 시간(초)에 랜덤하게 0 ~ 2포인트의 보정을 한 양이다 (3초 기도하면 회복량은 3 ~ 5 포인트). 단, 최대 MP 보다 더 회복하는 것은 불가능하다.
-인수에 “기도할 시간(초)"를 지정할 수 있고, 리턴 값은 “실제로 회복된 MP 양" 을 반환한다.
Cleric클래스를 테스트하는 ClericTest를 작성한다.
1. selfAid()의 hp회복을 확인
2. pray()의 mp회복을 확인(max값 이하로 회복)
-테스트 파일 만드는 방법에 대해 배웠다. main문을 수정하지 않고 다양한 테스트를 해볼 수 있다는 점이 흥미로웠다.
-final : 변경하지 않는 상수 선언
- 자바에서의 난수 생성
```   import java.util.Random;
Random random = new Random();
//0-2까지의 랜덤 상수 생성
int r = random.nextInt(3);```
아직은 Test 코드 작성에 어색함이 많다. 많은 경우의 수를 작성해보는 것이 도움이 될 것 같다.
> 250610_18_정해원

- src/main/java/com/survivalcoding/Cleric.java
- src/main/java/com/survivalcoding/Kinoko.java
- src/test/java/com/survivalcoding/ClericTest.java
- **교육 주제**:  생성자 선언과 static 선언의 이해
- 생성자 생성 개념 이해
- static 선언된 클래스 변수를 다른 함수에서 불러올 때 사용법 
- static 변수는 정적 변수로 다른 일반적인 멤버변수와 다른 메모리에 저장된다. 
- static 변수를 불러올 때는 해당 '함수이름.변수'로 불러옴
- `int hp` 는 기본형(Primitive Type)이기 때문에 Null 값 넣을 수 없다.
- `String name`은 참조형(Reference Type)이기 때문에 Null 값 넣는다. 
- `Hero` 변수 이름은 `Stack` 메모리에 저장되고, `Hero` class 안에 선언되어 있는 `hp =100`는 `Heap` 메모리에 저장되어 있다. 
- `Static` 이 선언된 변수는  데이터 영역 `data segment` 에 저장된다 함.  
- 전역 변수와 정적 변수의 차이점 및 개념
가볍게는 알겠다. 가볍게..!
> 250616_10_김소연

- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Cleric.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/ClericTest.java
1. Cleric클래스에 관하여, 2가지 수정을 하시오
현시점의 Cleric 클래스의 정의에는, 각 인스턴스별로 최대 HP와 최대 MP 필드에 대한 정보를 가지고 있다. 하지만, 모든 성직자의 최대 HP 는 50, 최대 MP 는 10으로 정해져 있어, 각 인스턴스가 각각의 정보를 가지는 것은 메모리 낭비이다. 
그래서, 최대 HP, 최대 MP의 필드가 공유 되도록 
필드 선언에 적절한 키워드를 추가하시오
2. 아래의 방침에 따라, 생성자를 추가 하시오
이 클래스는 new Cleric(“아서스", 40, 5) 와 같이, 이름, HP, MP 를 지정하여 인스턴스화 할 수 있다
이 클래스는 new Cleric(“아서스", 35) 와 같이, 이름과 HP만으로 지정하여 인스턴스화 할 수 있다. 이 때, MP는 최대 MP와 같은 값이 초기화 된다
이 클래스는 new Cleric(“아서스") 와 같이 이름만을 지정하여 인스턴스화 할 수 있다. 이 때, HP 와 MP 는 최대 HP와 최대 MP로 초기화 된다
이 클래스는 new Cleric() 과 같이 이름을 지정하지 않는 경우에는 인스턴스화 할 수 없다고 한다. (이름이 없는 성직자는 존재 할 수 없음)
생성자는 가능한 한 중복되는 코드가 없도록 작성한다
this
생성자에서 생성자를 호출하는 방법이 있었나 고민하게 되었다.
생성자에서 생성자 호출시 this로 호출이 가능하고 무조건 첫번째 줄에 와야한다.
아직까지 수월하다.
> 260616_03_강창환

- TIL/topics/java_basic/oop_1.md
- src/main/java/com/survivalcoding/ClassUML.puml
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Cleric.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Healable.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Person.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Wand.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Wizard.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/ClericTest.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/PersonTest.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/WandTest.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/WizardTest.java
- **교육 주제**: 
- [] Lint 체크
아직까지 할만하다.
> 250617_03_강창환

- src/main/java/com/survivalcoding/GreatWizard.java
- src/main/java/com/survivalcoding/Hero.java
- src/main/java/com/survivalcoding/Kinoko.java
- src/main/java/com/survivalcoding/Person.java
- src/main/java/com/survivalcoding/PosionSlime.java
- src/main/java/com/survivalcoding/Slime.java
- src/main/java/com/survivalcoding/SuperHero.java
- src/main/java/com/survivalcoding/Wand.java
- src/main/java/com/survivalcoding/Wizard.java
- src/main/java/com/survivalcoding/game.puml
- src/test/java/com/survivalcoding/GreatWizardTest.java
- src/test/java/com/survivalcoding/SuperHeroTest.java
- src/test/java/com/survivalcoding/WandTest.java
- **교육 주제**: 클래스 상속
테스트 코드 작성
부모 클래스의 메소드에 들어있는 변수를 자식 클래스에서 해당 메소드를 참조할 때 조작이 가능한지에 대한 의문
.
> 250623_05_김상엽

- src/homework/11.md
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/GreatWizard.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Hero.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/PoisonSlime.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Slime.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Sword.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Wand.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/Wizard.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/ClericTest.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/GreatWizardTest.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/PoisonSlimeTest.java
> 250623_07_이수현

- TIL/topics/git/상속.md
- src/main/java/practice250610/GreatWizard.java
- src/main/java/practice250610/Hero.java
- src/main/java/practice250610/PoisonSlime.java
- src/main/java/practice250610/Slime.java
- src/main/java/practice250610/Wizard.java
- src/test/java/practice250610/GreatWizardTest.java
- src/test/java/practice250610/PoisonSlimeTest.java
- src/test/java/practice250610/WizardTest.java
- **교육 주제**: 
- 상속 : 기능 확장
- 오버라이드( override ) : 함수 재정의
- Slime 클래스를 상속 받아 PoisonSlime 클래스 구현
- Slime의 attack( ) 함수를 재정의 하여 PoisonSlime의 attack( ) 함수 구현
- Wizard 클래스를 상속 받아 GreatWizard 클래스 구현
- Wizard의 heal( ) 함수를 재정의 하여 GreatWizard의 heal( ) 함수 구현
배우면 배울 수록 이전에 썼던 코드들이 지저분해 보인다
> 250623_12_이다영

- TIL/topics/java/inheritance.md
- src/main/java/com/survivalcoding/Game.puml
- src/main/java/com/survivalcoding/GreatWizard.java
- src/main/java/com/survivalcoding/Hero.java
- src/main/java/com/survivalcoding/PoisonSlime.java
- src/main/java/com/survivalcoding/Slime.java
- src/main/java/com/survivalcoding/Wand.java
- src/main/java/com/survivalcoding/Wizard.java
- src/test/java/com/survivalcoding/SlimeTest.java
- src/test/java/com/survivalcoding/WizardTest.java
**교육 주제**
클래스의 확장, 부모와 자식클래스, 인스턴스 메서드 우선도, super 와 super() 등 '상속' 의 기초개념을 습득
PoisonSlime 클래스와 GreatWizard 클래스는 각각 Slime 클래스와 Wizard 클래스로부터 상속받았음.
클래스를 상속받아 구현하는 방법은 대략적으로 다음과 같다.
```Java
public PoisonSlime extends Slime {
// Some codes, and constructors with super()
}
```
Test codes 의 테스트 결과 스크린샷
어려웠던 점 보다.. 슬슬 클래스 갯수가 늘어나니 Refactor 할 곳이 늘어나고 있음
- 기능의 구현 자체는 문제가 아니지만, 향후의 개발 과정에서 불편함이 없게 하는걸 염두하기 시작하면 너무 피곤해진다. 💤
맨 처음 설계를 깐깐하게 하고 들어가야 '🚨 어려웠던 점' 같은 고민을 안할 것
회고는 '💡 배운 점' 으로 갈음하겠음
> 250623_21_한승우

- TIL/topics/java/abstract and interface.md
- src/main/java/com/survivalcoding/Asset.java
- src/main/java/com/survivalcoding/Asset.puml
- src/main/java/com/survivalcoding/Book.java
- src/main/java/com/survivalcoding/Computer.java
- src/main/java/com/survivalcoding/IntangibleAsset.java
- src/main/java/com/survivalcoding/Patent.java
- src/main/java/com/survivalcoding/TangibleAsset.java
- src/main/java/com/survivalcoding/Thing.java
**교육 주제**  
- 개발 도중 당장의 구현이 어렵거나, 서비스 설계상 다양한 구현체를 포괄적으로 정의하는 개체의 필요성을 인식
- 앞서 제기된 해당 문제에 대해 `abstract` 와 `interface` 가 답안이 될 수 있음을 이해
- 과제를 통해 해당 사항을 복습
자산을 유형자산과 무형자산으로 분류, 이후 유형자산과 무형자산을 상속받은 클래스들에서 구현하는 순서로 작업
- .. 이 작업물은 어떤식으로 테스트해야 할 지 모르겠어서 테스트를 진행하지 못함
- (추상 클래스 자체를 꺼내쓸 수는 없으니) 컴파일 단계에서 '안돼' 빨간줄이 그어지는데 어떻게 테스트를
'📷 실행 결과' 두 번째 줄에 적은 내용과 동일
- (다른 이야기이지만) 자택에서 환경을 조성하느라 git을 포함한 기초 환경 세팅을 *의도치않게* 복습하였음, **윈도우 버전으로**
- 집에는 Temurin OpenJDK 21 을 설치
맨 처음 이 개념을 들었을 때 : '나중에 존재할' 것을 '지금 적어둔다' 는 느낌이었음, 묘함
> 250624_21_한승우

- src/main/java/Asset.java
- src/main/java/Book.java
- src/main/java/Computer.java
- src/main/java/Main.java
- src/main/java/TangibleAsset.java
- src/main/java/Thing.java
- src/main/java/UMLTEST.puml
- src/main/java/Usable.java
- **교육 주제**: 
추상 클래스는 뭔가 이해한것 같으면서도 못한것 같은 느낌이 들었다.
> 250624_22_손민석

- TIL/topics/Class/Abstract class_&&_Interface.md
- src/main/java/com/survivalcoding/game.puml
- src/main/java/com/survivalcoding/monster/FlyingMonster.java
- src/main/java/com/survivalcoding/monster/Goblin.java
- src/main/java/com/survivalcoding/monster/Monster.java
- src/main/java/com/survivalcoding/monster/WalkingMonster.java
- src/main/java/com/survivalcoding/monster/WarWolf.java
- src/main/java/com/survivalcoding/six/Asset.java
- src/main/java/com/survivalcoding/six/Book.java
- src/main/java/com/survivalcoding/six/Computer.java
- src/main/java/com/survivalcoding/six/TangibleAsset.java
- src/main/java/com/survivalcoding/six/Thing.java
- src/test/java/com/survivalcoding/six/AssetTest.java
- src/test/java/com/survivalcoding/six/BookTest.java
- src/test/java/com/survivalcoding/six/ComputerTest.java
- src/test/java/com/survivalcoding/six/TangibleAssetTest.java
- **교육 주제**: 추상 클래스와 인터페이스
- 공통적인 부분을 최대한 생각해보고자 했음
- 그 중에서 해당 클래스가 다른 클래스와 다른 점을 생각했음
- 인터페이스의 메서드는 모두 `public abstract` 가 내포되어있다는 것을 알았음
- 멤버는 `public static final`이 생략된 것을 알았음
- 자바에서 다중 상속은 불가능하지만 다중 implements는 가능하다는 것을 알았음
- class 다이어그램에서 추상 클래스와 인터페이스 그리는 법을 배움
- 항상 추상클래스와 인터페이스의 쓰임이 비슷해서 헷갈렸지만 이번 기회에 차이점에 대해 다시 생각해보는 시간을 가진 것 같다.
- 이를 기반으로 다음 유니티, 언리얼 프로젝트에 사용하고자 한다.
> 250624_14_윤주원

- TIL/topics/Class/Enum&&Generic.md
- TIL/topics/Class/Polymorphism.md
- src/main/java/com/survivalcoding/Cleric.java
- src/main/java/com/survivalcoding/eight/AuthState.java
- src/main/java/com/survivalcoding/eight/KeyType.java
- src/main/java/com/survivalcoding/eight/Pocket.java
- src/main/java/com/survivalcoding/eight/StrongBox.java
- src/main/java/com/survivalcoding/seven/A.java
- src/main/java/com/survivalcoding/seven/B.java
- src/main/java/com/survivalcoding/seven/X.java
- src/main/java/com/survivalcoding/seven/Y.java
- src/main/java/com/survivalcoding/seven/startcraft/IAttackUML.puml
- src/main/java/com/survivalcoding/seven/startcraft/IHealUML.puml
- src/main/java/com/survivalcoding/seven/startcraft/IHealable.puml
- src/main/java/com/survivalcoding/seven/startcraft/IRepair.puml
- src/main/java/com/survivalcoding/seven/startcraft/IRepairable.puml
- src/main/java/com/survivalcoding/seven/startcraft/ISheildable.puml
- src/main/java/com/survivalcoding/seven/startcraft/I자가치유.puml
- src/main/java/com/survivalcoding/seven/startcraft/Starcraft.puml
- src/test/java/com/survivalcoding/eight/StrongBoxTest.java
- **교육 주제**: Enum과 Generic
Enum으로 key타입을 구현하고 StrongBox에서 구현함
- 아직은 Enum을 받아와서 사용한다는 점이 어색하게 느껴짐
- 형이 정해지지 않았다는 점에서 편할거 같기도 하지만 값을 get,set할 때 오히려 정해지지 않았다는 점이 더 어렵게 느껴짐
- 제너릭 타입으로 E,T,K,V와 같이 다양한 것이 있는데, 이들의 사용 용도와 이유에 대해 공부했다.
- KeyType과 StrongBox를 하나의 패키지 안에 구현했는데 계속 오류가 발생함.
- 오류 로그를 확인해보니 같은 패키지가 아니라고 뜸
- 도저히 모르겠어서 gpt한테 물어보니 빌드 문제일 수도 있다고 해서 gradle 초기화 진행
- 잘됨
- 객체지향에 대해 하나씩 배워나가고 이를 유니티 프로젝트에 적용해보고 싶은 마음이 생겼다.
-  다음엔 다형성, enum 등 다양한 개념을 사용하고자 한다.
> 250702_14_윤주원

- TIL/topics/java_basic/제네릭, 열거형, 중첩클래스.md
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/generic/AuthState.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/generic/EnumMain.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/generic/KeyType.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/generic/Pocket.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/generic/StrongBox.java
- src/main/java/com/survivalcoding/assignments_01_instance/exam01/list/ListMain.java
- src/test/java/com/survivalcoding/assignments_01_instance/exam01/generic/StrongBoxTest.java
- **교육 주제**: 
- Generic
- Enum
- Inner Class
1. StrongBox 클래스에 열쇠의 종류를 나타내는 열거형 KeyType 정의
2. StrongBox 클래스 수정
- 열쇠의 종류를 나타내는 필드 변수
- 열쇠의 종류를 받는 생성자
단, 열쇠의 종류는 다음 4종류로 한정한다. 각 열쇠는 사용횟수의 한도가 정해져 있다.
> 1) PADLOCK (1,024회)
> 2) BUTTON (10,000회)
> 3) DIAL (30,000회)
> 4) FINGER (1,000,000회)
3. 금고에서 get() 메서드를 호출할 때 마다 사용횟수 카운트
4.  각 열쇠의 사용횟수에 도달하기 전에는 null을 리턴
각 열쇠의 사용 횟수를 비교하기 위해서 정해진 횟수를 줄 때 switch로 하면 된다는 걸 머리로는 알았는데 구현하는 데서 조금 걸렸다.
Generic을 사용해서 타입을 나중에 원하는 형태로 정의할 수 있다. 
열심히 하자.
**설계과제 소감** 
인터페이스, 추상클래스가 뭔지 개념을 알아도 정리가 안되는 느낌이었는데 과제를 하면서 조금은 도움이 된 것 같다.
> 250701_09_김민지

- src/main/java/com/survivalcoding/KeyType.java
- src/main/java/com/survivalcoding/StrongBox.java
- src/main/java/com/survivalcoding/generic/AuthState.java
- src/main/java/com/survivalcoding/generic/EnumMain.java
- src/main/java/com/survivalcoding/generic/Pocket.java
- **교육 주제**: 
제네릭유무에 대한 클래스 구현, 열거형(enum) 방법
테스트코드 작성하는 방법이 아직 너무 어렵다...
객체간 상속, 인터페이스에 대한 이해가 조금씩 늘어가는 기회가 된것같다
> 250701_17_엄승우
